function [paramsOut, varargout] = NQ_loadStruct(expFolder,varargin)
%NQ_loadStruct loads structure files generated by NET-QUANT

%initialize
NQdir = expFolder;
p.workdir = NQdir;
nArgin = length(varargin);
varargout = cell(1,nArgin);



for iArgin = 1:nArgin
    
        
        varargout{iArgin} = varargin{iArgin};
        
        
    if strcmp(varargin{iArgin}, 'ims')
        
        disp('loading images...');
        load([p.workdir filesep 'images' filesep 'ims.mat'])
        varargout{iArgin} = ims;
        
    elseif strcmp(varargin{iArgin}, 'masks')
        
        disp('loading binary masks...');
        load([p.workdir filesep 'masks' filesep 'masks.mat'])
        varargout{iArgin} = masks;
    
    elseif strcmp(varargin{iArgin}, 'labels')
        
        disp('loading label matrices...');
        load([p.workdir filesep 'labels' filesep 'labels.mat'])
        varargout{iArgin} = labels;
        
    elseif strcmp(varargin{iArgin}, 'analysis')
        
        disp('loading analysis...');
        load([p.workdir filesep 'analysis' filesep 'analysis.mat'])
        varargout{iArgin} = analysis;
        
    elseif strcmp(varargin{iArgin}, 'threshold')
        
        disp('loading threshold data...');
        load([p.workdir filesep 'threshold' filesep 'threshold.mat'])
        varargout{iArgin} = threshold;
        
    elseif strcmp(varargin{iArgin}, 'data')
        
        disp('loading output data...');
        load([p.workdir filesep 'data' filesep 'data.mat'])
        varargout{iArgin} = data;
    
    elseif strcmp(varargin{iArgin}, 'metadata')
        
        disp('loading metadata...');
        load([p.workdir filesep 'NQ_metadata.mat'])
        varargout{iArgin} = metadata;
        
    end
    
end

paramsOut = p;
end
